# rllama/integration/trl_wrapper.py

from typing import List, Dict, Any, Optional
import torch

# Assuming rllama modules are accessible from this path
# Adjust imports based on your final project structure
from rllama.rewards.composer import RewardComposer # Changed to import from rllama.rewards.composer
from rllama.rewards.shaping import RewardShaper # Corrected import based on previous file structure
from rllama.utils.config_loader import RewardConfigLoader, register_llm_components_if_not_present
from rllama.rewards.base import BaseReward # MODIFIED: Changed to absolute import
from rllama.rewards.normalization import Normalizer # MODIFIED: Changed to absolute import

class TRLRllamaRewardProcessor:
    """
    Processes prompts and responses to compute shaped rewards using RLlama
    for integration with TRL (Transformer Reinforcement Learning).
    """
    def __init__(self, 
                 rllama_config_path: str,
                 auto_register_llm_components: bool = True):
        """
        Initializes the TRLRllamaRewardProcessor.

        Args:
            rllama_config_path (str): Path to the RLlama YAML configuration file.
            auto_register_llm_components (bool): If True, automatically registers
                                                 RLlama's built-in LLM-specific reward components.
        """
        if auto_register_llm_components:
            register_llm_components_if_not_present() # Corrected: no argument needed

        self.loader = RewardConfigLoader(rllama_config_path)
        
        try:
            # Use the streamlined method to get composer and shaper
            self.composer, self.shaper = self.loader.create_composer_and_shaper()
            print("TRLRllamaRewardProcessor initialized successfully.")
            print(f"  Composer: {type(self.composer).__name__}")
            print(f"  Shaper: {type(self.shaper).__name__}")
        except Exception as e:
            print(f"Error initializing RLlama components from config '{rllama_config_path}': {e}")
            # Potentially re-raise or handle more gracefully
            raise
        # print(f"  Loaded components in composer: {list(self.composer.reward_components.keys())}")


    def compute_rewards(self,
                        prompts_text: List[str],
                        responses_text: List[str],
                        model_specific_infos: Optional[List[Dict[str, Any]]] = None
                       ) -> torch.Tensor:
        """
        Computes shaped rewards for a batch of prompts and responses.

        Args:
            prompts_text (List[str]): A list of prompt strings.
            responses_text (List[str]): A list of response strings generated by the model.
            model_specific_infos (Optional[List[Dict[str, Any]]]): 
                A list of dictionaries, where each dictionary can contain
                additional model-specific information (e.g., logprobs, hidden states)
                for the corresponding prompt-response pair. This info will be
                added to the context for reward calculation.

        Returns:
            torch.Tensor: A tensor of scalar shaped reward values, one for each input pair.
        """
        if not (len(prompts_text) == len(responses_text)):
            raise ValueError("Length of prompts_text and responses_text must be the same.")
        if model_specific_infos and not (len(prompts_text) == len(model_specific_infos)):
            raise ValueError("Length of model_specific_infos must match prompts_text if provided.")

        batch_rewards = []
        batch_detailed_infos = [] # To store detailed reward info

        for i in range(len(prompts_text)):
            # 1. Construct context for RLlama components
            context = {
                "prompt": prompts_text[i],
                "response_text": responses_text[i],
                # Add any other standard context items you expect LLM components to use
            }
            if model_specific_infos and model_specific_infos[i] is not None:
                context.update(model_specific_infos[i])

            # 2. Get raw (unweighted, unnormalized) rewards from RewardComposer
            # The composer's calculate method should return a dict including 'total_reward'
            # and 'component_rewards' (a dict of {name: raw_score}).
            # composed_info = self.composer.calculate(context) # OLD LINE
            # MODIFIED: Call compute_rewards instead of calculate
            # Also, compute_rewards returns a tuple: (all_raw_rewards, all_detailed_infos)
            batch_raw_rewards_list, batch_detailed_infos_list = self.composer.compute_rewards(
                prompts=[context["prompt"]], # compute_rewards expects lists
                responses=[context["response_text"]], # compute_rewards expects lists
                **context # Pass other context items as kwargs
            )
            # Assuming we are processing one item at a time in this loop for now
            # If TRLRllamaRewardProcessor processes item by item in the loop:
            raw_component_rewards = batch_raw_rewards_list[0] if batch_raw_rewards_list else {}
            # composed_info needs to be structured based on what shaper expects.
            # Let's assume shaper needs individual component rewards.
            # The 'total_reward' might need to be summed if not directly provided by compute_rewards in that format.
            # For now, let's pass component rewards. The shaper might need adjustment too.

            # This part needs careful review based on what shaper.shape expects and what composer.compute_rewards provides.
            # The current RewardComposer.compute_rewards returns:
            # Tuple[List[Dict[str, float]], List[Dict[str, Any]]]
            # which are lists of dicts (one per item in batch).
            # Since the loop in trl_wrapper is per item, we take the first element.

            # 3. Prepare input for RewardShaper
            # The shaper's shape method takes the raw rewards and the context.
            # It handles normalization, weighting, and final composition.
            # We pass the full context in case the shaper or its sub-modules need it.

            # Placeholder for total_reward if shaper needs it explicitly and it's not part of raw_component_rewards
            # This logic might need to be more sophisticated depending on shaper's needs.
            raw_total_reward_for_item = sum(raw_component_rewards.values())


            shaped_reward, shaping_details = self.shaper.shape(
                raw_total_reward_for_item, # Or pass the whole composed_info
                raw_component_rewards, # Pass the dict of raw component rewards for the current item
                context
            )
            
            batch_rewards.append(shaped_reward)
            
            # Store detailed info for potential logging/debugging
            detailed_info_for_instance = {
                "prompt": prompts_text[i],
                "response": responses_text[i],
                "raw_component_rewards": composed_info["component_rewards"],
                "raw_total_reward": composed_info["total_reward"],
                "shaped_reward": shaped_reward,
                "shaping_details": shaping_details # e.g., normalized scores, weighted scores
            }
            batch_detailed_infos.append(detailed_info_for_instance)

        # Optionally, you might want to return batch_detailed_infos as well,
        # or log it, or make it accessible via a property.
        # For TRL, only the tensor of rewards is strictly needed for ppo_trainer.step().
        self._last_batch_detailed_infos = batch_detailed_infos # Store for inspection

        return torch.tensor(batch_rewards, dtype=torch.float32)

    def get_last_batch_detailed_infos(self) -> List[Dict[str, Any]]:
        """
        Returns detailed reward information from the most recent call to compute_rewards.
        """
        return getattr(self, "_last_batch_detailed_infos", [])

    def reset_components(self):
        """
        Resets any stateful reward components and the reward shaper (e.g., normalizers).
        This should be called typically at the end of an epoch or training phase.
        """
        self.composer.reset_components()
        self.shaper.reset()
        print("TRLRllamaRewardProcessor components and shaper reset.")