# rllama/integration/trl_wrapper.py

from typing import List, Dict, Any
import torch
from rllama.utils.config_loader import load_reward_system

class TRLRlamaRewardProcessor:
    """
    A wrapper to seamlessly integrate the RLlama reward system with
    the TRL PPOTrainer.

    This class is initialized with the path to a reward config file and
    provides a `compute_reward` method that can be directly passed to the
    PPOTrainer.
    """
    def __init__(self, config_path: str):
        """
        Args:
            config_path (str): The file path to the YAML reward configuration.
        """
        self.composer, self.shaper = load_reward_system(config_path)
        self.current_step = 0

    def compute_reward(
        self,
        responses: List[str],
        prompts: List[str] = None,
        infos: List[Dict[str, Any]] = None
    ) -> torch.Tensor:
        """
        This method is designed to be passed to the TRL PPOTrainer's
        `compute_reward` argument.

        It computes a reward for each response in the batch.

        Args:
            responses (List[str]): A list of text responses generated by the model.
            prompts (List[str], optional): A list of the corresponding prompts.
            infos (List[Dict[str, Any]], optional): Additional info per response.

        Returns:
            torch.Tensor: A tensor of scalar rewards for each response in the batch.
        """
        rewards = []
        for i, response in enumerate(responses):
            # Create a flexible context dictionary for each item in the batch.
            # Reward components can access any of this information.
            context = {
                "response": response,
                "prompt": prompts[i] if prompts else None,
                "info": infos[i] if infos else None,
                "step": self.current_step,
            }

            # 1. Calculate raw rewards for all components
            component_rewards = self.composer.calculate(context)

            # 2. Apply weights and shaping to get the final reward
            final_reward = self.shaper.shape(component_rewards, step=self.current_step)
            
            rewards.append(torch.tensor(final_reward, dtype=torch.float32))

        # Increment the step counter after processing a batch
        self.current_step += 1
        
        return torch.stack(rewards)